### ISSUE TITLE
Image transformation #2

### ISSUE THREAD

**Issue by lmolinario** [IlPodd/flask-classification-2022-G#5]
## Summary of the request
Create a handler that allows picking an image and set parameters for an image transformation (https://pillow.readthedocs.io/en/stable/reference/ImageEnhance.html). The user should be allowed to specify the color, brightness, contrast, and sharpness to apply to the original image. The transformed image should appear in the output interface. **This is a new feature. Old functionalities must be preserved.** Difficulty: ![image](https://user-images.githubusercontent.com/23276849/147104730-4e12bcde-b532-4363-ac73-1ebdd1850629.png)
 
## Subtasks

- [x] * Copy the classification API interface.
- [x] * Create a form for selecting the transformation.
- [x] * Implement the API that applies the transformation to the selected image.
- [x] * Implement the visualization of results.

## Plan for the implementation
 Modify the code such that the new interface shows the dropdown menu to select the image, the submit button, and a NEW field that allows specifying values for the transformation to apply. The values for the transformation should have default values, but should be editable by the user. Use Flask forms to create the interface for selecting the transformation. Use correct field types for the inputs. It is not required to use queues. The API can be implemented as showing the form if a GET request is issued, and the results if the POST is validated.
 
Useful links:
 
* https://pillow.readthedocs.io/en/stable/reference/ImageEnhance.html
* [Flask form fields](https://wtforms.readthedocs.io/en/2.3.x/fields/)

**Comment by francescoaracu** [comment]
Subtasks 1 and 2 done with commit [5f9f4f1](https://github.com/IlPodd/flask-classification-2022-G/commit/5f9f4f1515a618c5c4a4a8498246513438e80f06).

![image](https://github.com/IlPodd/flask-classification-2022-G/assets/48188510/a885b485-eb63-4a08-a7ae-1748c56819c6)

**Comment by francescoaracu** [comment]
Subtasks 3 and 4 done with commit [cda8b84](https://github.com/IlPodd/flask-classification-2022-G/commit/cda8b841eddec3deba0c392959771dbe3511453f).

![image](https://github.com/IlPodd/flask-classification-2022-G/assets/48188510/ea96d221-3c63-47b2-9de8-2b631a140720)
